Делает разметку главной страницы
htmlacademy-htmlcss/1971775-device-33 pull request #2
Opened 2022-01-25 18:34 UTC by 1skor1

Здравствуйте! Сделала разметку главной страницы.

2022-01-26 08:38 UTC, ant1quar requested changes
В целом - неплохо, но нужно немного допилить.

2022-01-26 08:38 UTC, ant1quar commented on index.html
> +              </ul>
Зачем тут ul li, если тут один элемент?

2022-01-26 08:38 UTC, ant1quar commented on index.html
> +         </ul>
Зачем тут ul li, если тут один элемент?

2022-01-26 08:38 UTC, ant1quar commented on index.html
> +                </div>
инпуты надо в форму обернуть, но тут инпуты не нужны, это скорее button, которые стилизованы под radio

2022-01-26 08:38 UTC, ant1quar commented on index.html
> +           </table>
лучше тут не использовать таблицу, пока задачи мобильной версии не стоит, но после расположить один элемент под другим будет невозможно.
Сделай число и подпись под ним одним блоком

2022-01-26 08:38 UTC, ant1quar commented on index.html
> +        <input class="services-slider  visually-hidden" id="services-control-2" type="radio" name="services-control">
Тоже кнопки с текстом

2022-01-26 08:38 UTC, ant1quar commented on index.html
> +        <label class="services-slider-control" for="services-control-3">Кредит</label>
Вот тут прямо кнопки

2022-01-26 08:38 UTC, ant1quar commented on index.html
> +        <p>Мы с удовольствием доставим ваш товар прямо
А почему классов на этих элементах нет?

2022-01-26 08:38 UTC, ant1quar commented on index.html
> +        <a class="main-delivery-item-link" href="#">
зачем тут ссылка?

2022-01-26 08:38 UTC, ant1quar commented on index.html
> +      <div class="page-footer-links-wrap"></div>
зачем пустой див?

2022-01-26 16:43 UTC, 1skor1 commented
Спасибо за обратную связь! Надеюсь я все правильно поняла и исправила.

2022-01-27 15:57 UTC, merged

2022-01-28 01:20 UTC, ant1quar commented
Да, все хорошо. Успехов на курсе! 
Добавляйся в телеграм ко мне для быстрой связи.